name: Deploy To S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: .env 파일 만들기
        run: echo "${{ secrets.ENV_FILE }}" > ./.env

      - name: Install deps
        run: npm ci

      - name: Build (Next static export)
        run: |
          npm run build
          # Next 14/15에서 output:'export'면 build 시 out/ 생성
          # 만약 안 생기면 npx next export 추가

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Sync to S3
        run: |
          aws s3 sync ./out/ s3://${{ secrets.AWS_BUCKET_NAME }}/ --delete --exclude ".DS_Store"

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"